services:
  ecommerce-nextjs:
    container_name: ecommerce-nextjs
    build: ../ecommerce-nextjs-example-store
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - ../ecommerce-nextjs-example-store/.env.local
