cache_resources:
  - label: view_states
    memcached:
      addresses:
        - memcached:11211
      default_ttl: 3600s

input:
  kafka:
    addresses: ["redpanda:9092"]
    topics: ["snowplow-enriched-good"]
    consumer_group: "discounts-processor"

pipeline:
  processors:
    - log:
        level: INFO
        message: "Received event: ${! this }"

    - mapping: |
        meta "user_id" = this.user_id
        meta "webpage_id" = this.webpage_id
        meta "event_name" = this.event_name
        meta "collector_tstamp" = this.collector_tstamp
        meta "discount_generated" = false
        root = this

    - log:
        level: INFO
        message: "Extracted metadata: user_id=${! this.user_id }, webpage_id=${! this.webpage_id }, event_name=${! this.event_name }"

    - switch:
        - check: this.event_name == "snowplow_ecommerce_action"
          processors:
            - log:
                level: INFO
                message: "Processing snowplow_ecommerce_action event for user_id=${! this.user_id }, webpage_id=${! this.webpage_id }"

            - mapping: |
                root = {
                  "user_id": this.user_id,
                  "webpage_id": this.webpage_id,
                  "product_id": this.product_id,
                  "start_time": this.collector_tstamp
                }

            - cache:
                resource: view_states
                operator: set
                key: ${! this.user_id }_${! this.webpage_id }
                value: ${! this }

            - log:
                level: INFO
                message: "View state stored for user_id=${! this.user_id }, webpage_id=${! this.webpage_id }"

        - check: this.event_name == "page_ping"
          processors:
            - log:
                level: INFO
                message: "Processing page_ping event for user_id=${! this.user_id }, webpage_id=${! this.webpage_id }"

            - cache:
                resource: view_states
                operator: get
                key: ${! this.user_id }_${! this.webpage_id }

            - log:
                level: INFO
                message: "Retrieved event from cache"

            - try:
                - mapping: |
                    meta "duration_seconds" = 0

                    if this != null && this.webpage_id == this.webpage_id {
                      let start = this.start_time.ts_unix()
                      let current = meta("collector_tstamp").ts_unix()

                      let duration = $current - $start
                      meta "duration_seconds" = $duration

                      if $duration >= 90 {
                        meta "discount_generated" = true
                        root = {
                          "shopper_id": this.user_id,
                          "product_id": this.product_id,
                          "discount": 0.1
                        }
                      }
                    }

                - log:
                    level: INFO
                    message: "Duration calculated: ${! meta(\"duration_seconds\") } seconds, Discount applied: ${! meta(\"discount_generated\") }"

            - catch:
                - log:
                    level: ERROR
                    message: "Error processing page_ping for user_id=${! meta(\"user_id\") }, webpage_id=${! meta(\"webpage_id\") }. Reason: ${! error() }"

    - log:
        level: INFO
        message: "Final result: ${! if meta(\"discount_generated\") == true { \"A discount was generated for ${ !this } \" } else { \"No action\" } }"

    - mapping: |
        root = if meta("discount_generated") == false {
          deleted()
        }

output:
  kafka:
    addresses: ["redpanda:9092"]
    topic: "shopper-discounts"
    max_in_flight: 1
    key: ${! meta("user_id") }
